### ISSUE TITLE
Cuda Extention

### ISSUE THREAD

**Issue by sycasia** [NJU-3DV/Relightable3DGaussian#3]
Thanks for sharing the codes. I have a question that since the pytorch was installed with cudatoolkit==11.6, in the next step of bvh installation, do we need to change the version of cudatoolkit to 11.8 or others? Thanks for replying!

**Comment by yGaoJiany** [comment]
In my case, I created a virtual environment using conda, where pytorch and cudatoolkit==11.6 were installed using conda. However, I downloaded and installed another CUDA 11.8 from [Nvidia](https://developer.nvidia.com/cuda-11-8-0-download-archive) and configured it to the environment variables. I then compiled the CUDA extensions and they work fine.

**Comment by origamiman72** [comment]
Hi, which env. variables did you set? I was able to get simple-knn and r3dg-rasterization to compile by setting `export PYTHONNOUSERSITE=True` but bvh-tracing outputs `RuntimeError: Compiling Objects for extension` and fails.

**Comment by yGaoJiany** [comment]
Could you please provide more information on this? For example, the output of the terminal.

**Comment by origamiman72** [comment]
This was the full output:
```
Processing ./bvh
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: bvh-tracing
  Building wheel for bvh-tracing (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [172 lines of output]
      running bdist_wheel
      running build
      running build_ext
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'bvh_tracing._C' extension
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh
      creating /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src
      Emitting ninja build file /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/4] /opt/cuda/bin/nvcc  -I/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/TH -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/THC -I/opt/cuda/include -I/home/ahuja/.conda/envs/r3dg/include/python3.7m -c -c /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/trace.cu -o /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/trace.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
      [2/4] c++ -MMD -MF /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.o.d -pthread -B /home/ahuja/.conda/envs/r3dg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/TH -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/THC -I/opt/cuda/include -I/home/ahuja/.conda/envs/r3dg/include/python3.7m -c -c /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.cpp -o /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      FAILED: /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.o
      c++ -MMD -MF /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.o.d -pthread -B /home/ahuja/.conda/envs/r3dg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/TH -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/THC -I/opt/cuda/include -I/home/ahuja/.conda/envs/r3dg/include/python3.7m -c -c /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.cpp -o /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:45,
                       from /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bindings.cpp:1:
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:199:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
        199 |     std::uint16_t nargs;
            |          ^~~~~~~~
            |          wint_t
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:202:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
        202 |     std::uint16_t nargs_kw_only = 0;
            |          ^~~~~~~~
            |          wint_t
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:205:10: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
        205 |     std::uint16_t nargs_pos_only = 0;
            |          ^~~~~~~~
            |          wint_t
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h: In constructor ‘pybind11::detail::function_call::function_call(const pybind11::detail::function_record&, pybind11::handle)’:
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:310:20: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs’; did you mean ‘args’?
        310 |     args.reserve(f.nargs);
            |                    ^~~~~
            |                    args
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:311:28: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs’; did you mean ‘args’?
        311 |     args_convert.reserve(f.nargs);
            |                            ^~~~~
            |                            args
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h: In function ‘void pybind11::detail::process_kw_only_arg(const pybind11::arg&, function_record*)’:
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:382:10: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs_kw_only’
        382 |     ++r->nargs_kw_only;
            |          ^~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h: In static member function ‘static void pybind11::detail::process_attribute<pybind11::pos_only>::init(const pybind11::pos_only&, pybind11::detail::function_record*)’:
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:439:12: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs_pos_only’
        439 |         r->nargs_pos_only = static_cast<std::uint16_t>(r->args.size());
            |            ^~~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/attr.h:439:46: error: ‘uint16_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
        439 |         r->nargs_pos_only = static_cast<std::uint16_t>(r->args.size());
            |                                              ^~~~~~~~
            |                                              wint_t
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h: In member function ‘void pybind11::cpp_function::initialize_generic(unique_function_record&&, const char*, const std::type_info* const*, pybind11::size_t)’:
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:311:26: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs_kw_only’
        311 |                 if (rec->nargs_kw_only > 0 && arg_index + rec->nargs_kw_only == args)
            |                          ^~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:311:64: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs_kw_only’
        311 |                 if (rec->nargs_kw_only > 0 && arg_index + rec->nargs_kw_only == args)
            |                                                                ^~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:329:26: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs_pos_only’
        329 |                 if (rec->nargs_pos_only > 0 && (arg_index + 1) == rec->nargs_pos_only)
            |                          ^~~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:329:72: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs_pos_only’
        329 |                 if (rec->nargs_pos_only > 0 && (arg_index + 1) == rec->nargs_pos_only)
            |                                                                        ^~~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:371:14: error: ‘struct pybind11::detail::function_record’ has no member named ‘nargs’; did you mean ‘args’?
        371 |         rec->nargs = (std::uint16_t) args;
            |              ^~~~~
            |              args
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:371:28: error: ‘uint16_t’ is not a member of ‘std’; did you mean ‘wint_t’?
        371 |         rec->nargs = (std::uint16_t) args;
            |                            ^~~~~~~~
            |                            wint_t
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h: In static member function ‘static PyObject* pybind11::cpp_function::dispatcher(PyObject*, PyObject*, PyObject*)’:
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:604:40: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs’; did you mean ‘args’?
        604 |                 size_t num_args = func.nargs;    // Number of positional arguments that we need
            |                                        ^~~~~
            |                                        args
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:607:51: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs_kw_only’
        607 |                 size_t pos_args = num_args - func.nargs_kw_only;
            |                                                   ^~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:657:40: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs_pos_only’
        657 |                 if (args_copied < func.nargs_pos_only) {
            |                                        ^~~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:658:47: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs_pos_only’
        658 |                     for (; args_copied < func.nargs_pos_only; ++args_copied) {
            |                                               ^~~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:672:44: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs_pos_only’
        672 |                     if (args_copied < func.nargs_pos_only)
            |                                            ^~~~~~~~~~~~~~
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/pybind11/pybind11.h:760:53: error: ‘const struct pybind11::detail::function_record’ has no member named ‘nargs’; did you mean ‘args’?
        760 |                     second_pass_convert.resize(func.nargs, false);
            |                                                     ^~~~~
            |                                                     args
      [3/4] /opt/cuda/bin/nvcc  -I/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/TH -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/THC -I/opt/cuda/include -I/home/ahuja/.conda/envs/r3dg/include/python3.7m -c -c /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/construct.cu -o /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/construct.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
      [4/4] /opt/cuda/bin/nvcc  -I/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/TH -I/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/THC -I/opt/cuda/include -I/home/ahuja/.conda/envs/r3dg/include/python3.7m -c -c /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bvh.cu -o /home/ahuja/dev/mphil/Relightable3DGaussian/bvh/build/temp.linux-x86_64-cpython-37/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/src/bvh.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

      /home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/include/c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1814, in _run_ninja_build
          env=env)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/subprocess.py", line 512, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ahuja/dev/mphil/Relightable3DGaussian/bvh/setup.py", line 28, in <module>
          'build_ext': BuildExtension,
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 595, in unix_wrap_ninja_compile
          with_cuda=with_cuda)
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1492, in _write_ninja_file_and_compile_objects
          error_prefix='Error compiling objects for extension')
        File "/home/ahuja/.conda/envs/r3dg/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bvh-tracing
  Running setup.py clean for bvh-tracing
Failed to build bvh-tracing
ERROR: Could not build wheels for bvh-tracing, which is required to install pyproject.toml-based projects

```

**Comment by mxgbs** [comment]
I got the similar error, but it's when compile /r3dg-rasterization

**Comment by 2019213039** [comment]
I got the same error when I try to install bvh-tracing

**Comment by Aureliano-qwer** [comment]
I encountered a similar problem, but my CUDA version is 12.1. Can the BVH source code be modified to adapt to higher versions of cuda?
`/usr/local/cuda/include/cuda/std/detail/libcxx/include/type_traits:4405:16: error: static assertion failed: Attempt to use an extended __device__ lambda in a context that requires querying its return type in host code. Use a named function object, a __host__ __device__ lambda, or cuda::proclaim_return_type instead.
       4405 |   static_assert(!__nv_is_extended_device_lambda_closure_type(_Fp),
            |               ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by RaymondJiangkw** [comment]
Hi, it works in my case with CUDA version 12.1 by specifying the return type of lambda functions using `cuda::proclaim_return_type` in the source code.

**Comment by WhiteLoTe** [comment]
in the bvh/src/constructor. cu,I replaced the 

```
    const auto aabb_whole = thrust::reduce(
            aabbs_ptr + num_internal_nodes, aabbs_ptr + num_nodes, default_aabb,
            [] __device__ (const aabb_type& lhs, const aabb_type& rhs) {
                return merge(lhs, rhs);
            });
```


  with 

```
    const auto aabb_whole = thrust::reduce(
            aabbs_ptr + num_internal_nodes, aabbs_ptr + num_nodes, default_aabb,
            [] __host__ __device__ (const aabb_type& lhs, const aabb_type& rhs) { // <-- 更改为 __host__ __device__
                return merge(lhs, rhs);
            });
```



 to solve this problem.
