### ISSUE TITLE
AssertionError: Could not recognize scene type!

### ISSUE THREAD

**Issue by arihara5** [NJU-3DV/Relightable3DGaussian#44]
Traceback (most recent call last):
  File "D:\hml\Relightable3DGaussian-main\train.py", line 409, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), is_pbr=is_pbr)
  File "D:\hml\Relightable3DGaussian-main\train.py", line 34, in training
    scene = Scene(dataset, gaussians)
  File "D:\hml\Relightable3DGaussian-main\scene\__init__.py", line 64, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!
Could you help me to solve this error?

**Comment by zouyanmei** [comment]
You should check the path of the datasets.
